api_platform:
    title: La Boutique Fran√ßaise API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    docs_formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    enable_swagger_ui: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']